"""empty message

Revision ID: 696330c1918f
Revises: 
Create Date: 2020-04-13 07:02:51.646050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696330c1918f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=10), nullable=True),
    sa.Column('night_time_on', sa.Integer(), nullable=True),
    sa.Column('night_time_off', sa.Integer(), nullable=True),
    sa.Column('night_mode_type', sa.String(length=10), nullable=True),
    sa.Column('font_size', sa.String(length=3), nullable=True),
    sa.Column('coding_addon', sa.Integer(), nullable=True),
    sa.Column('hyperlinks_addon', sa.Integer(), nullable=True),
    sa.Column('colors_addon', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    # ### end Alembic commands ###
